<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends EntityRepository
{
    /**
     * @return array
     */
    public function getAllArticles()
    {
        $queryBuilder = $this->createQueryBuilder("a")
            ->leftJoin('a.image','i')
            ->addSelect('i')
            ->leftJoin('a.categorie','c')
            ->addSelect('c');

        $query = $queryBuilder->getQuery();
        return $query->getResult();
    }

    /**
     * @param $nbArticlePage
     * @param $page
     * @return Paginator
     */
    public function getArticlesPages($nbArticlePage,$page)
    {
        $queryBuilder = $this->createQueryBuilder("a")
            ->leftJoin('a.image','i')
            ->addSelect('i')
            ->leftJoin('a.categorie','c')
            ->addSelect('c')
            ->where('a.publication=:publication')
            ->setParameter('publication',1)
            ->orderBy('a.titre','ASC')
            ->setFirstResult(($page-1)*$nbArticlePage)
            ->setMaxResults($nbArticlePage)
        ;
        return new Paginator($queryBuilder);

    }
}
